name: Logging event details
on: [issues, workflow_dispatch]
jobs:
   logIssue:
      runs-on: ubuntu-latest
      steps:
         - name: Logging event details
           run: echo "${{github.event}}"
