name: Logging event details
on: [issues, workflow_dispatch]
jobs:
   logIssu:
      runs-on: ubuntu-latest
      steps:
         - name: Logging event details
           run: echo "${{toJson(github.event_name) }}"
